export const menu = [
  {
    id: 1,
    title: "Buttermilk Pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Our signature house-made buttermilk pancake, topped with whipped butter and served with Slopeside Pure Vermont Maple Syrup. `,
  },
  {
    id: 2,
    title: "Diner Double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `High quality beef medium to well with cheese and bacon on a multigrain bun. `,
  },
  {
    id: 3,
    title: "Godzilla Milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Vanilla ice cream, lotus biscoff, milk powder, fresh milk and toasted marshmallow on top.`,
  },
  {
    id: 4,
    title: "Country Delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Toasted rye bread,beetroot and cottage cheese,baby spinach,cherry vine tomato, alfa alfa sprout ,chill jam. `,
  },
  {
    id: 5,
    title: "Egg Attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `A huge single or triple burger with all the fixings, cheese, egg, lettuce, tomato, onions and special sauce or mayonnaise! `,
  },
  {
    id: 6,
    title: "Oreo Dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Vanilla ice cream, milk powder, oreo cookies & fresh milk.`,
  },
  {
    id: 7,
    title: "Bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Gorgonzola cheese, plum tomatoes and fresh thyme partner with applewood bacon, fried eggs and toasted sourdough bread for a sandwich that will wake up tired taste buds. `,
  },
  {
    id: 8,
    title: "American classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Juicy, big, loaded with toppings of your choice.  `,
  },
  {
    id: 9,
    title: "Sugar paradise",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Vanilla ice cream, caramel syrup, nutella, milk powder, fresh milk and toasted marshmallow on top.`,
  },
  {
    id: 10,
    title: "Bison steak",
    category: "dinner",
    price: 22.99,
    img: "./images/item-10.jpeg",
    desc: `100% Grass Fed and Finished Bison Steaks & Roasts. Smooth, consistent tenderness & quality with added depth of flavor.`,
  }, 
  {
    id: 11,
    title: "Grilled shrimps",
    category: "dinner",
    price: 26.99,
    img: "./images/item-11.jpeg",
    desc: `Shrimps on top of rice pilaf. Served with drawn butter and lemon. Choice of soup or salad and choice of loaded baked potato, grilled veggies, steak fries, sweet potato fries or rice pilaf.`,
  },
  {
    id: 12,
    title: "Sunny Saffron Butter Pasta",
    category: "dinner",
    price: 20.99,
    img: "./images/item-12.jpeg",
    desc: `A little saffron goes a long way in this standout sauce, finished with cracked pepper, salty Parmesan, and fragrant basil.`,
  },
  {
    id: 13,
    title: "Peach and Prosciutto Sandwich",
    category: "lunch",
    price: 12.99,
    img: "./images/item-13.jpeg",
    desc: `Juicy sweet peaches are leveled up with chili crisp and vinegar, becoming the star ingredient in this summer sandwich.`,
  },
  {
    id: 14,
    title: "Chilled Beet and Yogurt Soup",
    category: "lunch",
    price: 10.99,
    img: "./images/item-14.jpeg",
    desc: `Beat the heat with this incredibly vibrant, wildly simple, and refreshingly cold beet soup.`,
  },
  {
    id: 15,
    title: "Sour Cherry Cheesecake",
    category: "dessert",
    price: 7.99,
    img: "./images/item-15.jpeg",
    desc: `Tangy sour cherries meet sweet and pillowy cheesecake in the ultimate spring-to-summer dessert.`,
  },
  {
    id: 16,
    title: "Chocolate Soufflé Fit for a Crowd",
    category: "dessert",
    price: 6.99,
    img: "./images/item-16.jpeg",
    desc: `This larger-than-life gluten-free chocolate soufflé gets a flavor boost from nutty brown butter.`
},
{
  id: 16,
  title: "Banana Cupcakes With Peanut Butter Frosting",
  category: "dessert",
  price: 4.99,
  img: "./images/item-17.jpeg",
  desc: `These cupcakes, slathered with rich peanut butter frosting.`
}
];
